CREATE TABLE syn20338157
 SELECT ID, MAX(TIMESTAMP) AS TIMESTAMP
 FROM  NODE_SNAPSHOT
 WHERE PARENT_ID = 20338157
 GROUP BY ID;

TRUNCATE TABLE syn20338157;
 
INSERT INTO syn20338157 (ID, TIMESTAMP)
SELECT ID, MAX(TIMESTAMP) AS TIMESTAMP
FROM  NODE_SNAPSHOT
WHERE PARENT_ID = 20338157
GROUP BY ID;

SELECT PAR.ENTITY_ID, AR.USER_ID, COUNT(*)
 FROM PROCESSED_ACCESS_RECORD PAR, ACCESS_RECORD AR,
 (SELECT ID, CREATED_BY FROM NODE_SNAPSHOT WHERE (ID, TIMESTAMP) IN (SELECT ID, TIMESTAMP FROM syn20338157)) AS NODE
  WHERE PAR.SESSION_ID = AR.SESSION_ID
 AND PAR.TIMESTAMP = AR.TIMESTAMP
 AND PAR.ENTITY_ID = NODE.ID
 AND PAR.NORMALIZED_METHOD_SIGNATURE IN ('GET /entity/#/file','GET /entity/#/version/#/file')
 AND AR.TIMESTAMP BETWEEN unix_timestamp(curdate())*1000 - (50*24*60*60*1000) AND  unix_timestamp(curdate())*1000
 GROUP BY PAR.ENTITY_ID,  AR.USER_ID;
 
 
SELECT NODE.ID, FDR.USER_ID ,COUNT(*)
FROM FILE_DOWNLOAD_RECORD FDR,
(SELECT ID, CREATED_BY FROM NODE_SNAPSHOT WHERE (ID, TIMESTAMP) IN (SELECT ID, TIMESTAMP FROM syn20338157)) AS NODE
WHERE FDR.ASSOCIATION_OBJECT_ID = NODE.ID
AND FDR.ASSOCIATION_OBJECT_TYPE = "FileEntity"
AND FDR.TIMESTAMP BETWEEN unix_timestamp(curdate())*1000 - (50*24*60*60*1000) AND  unix_timestamp(curdate())*1000
GROUP BY NODE.ID, FDR.USER_ID;